name: Build and deploy Node.js app to Azure Web App - codebreakerchatbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build (if applicable)
        run: npm run build --if-present

      - name: Test (if applicable)
        run: npm run test --if-present

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Azure login via Service Principal
        uses: azure/login@v2
        with:
          auth-type: 'SERVICE_PRINCIPAL'
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'codebreakerchatbot'  # Replace with your Azure Web App name
          slot-name: 'Production'
          package: .

      - name: Set environment variables in Azure
        run: |
          az webapp config appsettings set --name codebreakerchatbot --resource-group Chatbot --settings GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
